/**
 * Created by Zychaowill on 2017/04/21 11:22
 */
export const FIND_COALMINE_BASE_INFO = 'FIND_COALMINE_BASE_INFO';
export const COUNT_REALTIME_INFO = 'COUNT_REALTIME_INFO';

export const FIND_UNIT_STAFF_BY_UNITID = 'FIND_UNIT_STAFF_BY_UNITID';
export const MAP_UNIT_STAFF_BY_UNITID = 'MAP_UNIT_STAFF_BY_UNITID';

export const FIND_REGION_STAFF_BY_REGIONID = 'FIND_REGION_STAFF_BY_REGIONID';
export const FIND_EVACUATE_STAFF_BY_REGIONID = 'FIND_EVACUATE_STAFF_BY_REGIONID';

export const FIND_ALARM_BASE_INFO = 'FIND_ALARM_BASE_INFO';
